In [1]:
# Assignment 2
# Bag of Words (Count Occurrence)

# Bag of Words (Normalized Count)

# TF–IDF

# Word2Vec Embeddings

# Install Required Libraries

In [1]:
!pip install numpy
!pip install pandas
!pip install gensim
!pip install scikit-learn


Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
  Using cached gensim-4.4.0.tar.gz (23.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached smart_open-7.5.0-py3-none-any.whl.metadata (24 kB)
  Using cached wrapt-2.0.1-cp314-cp314-win_amd64.whl.metadata (9.2 kB)
Using cached smart_open-7.5.0-py3-none-any.whl (63 kB)
Using cached wrapt-2.0.1-cp314-cp314-win_amd64.whl (60 kB)
Failed to build gensim


  error: subprocess-exited-with-error
  
  × Building wheel for gensim (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [716 lines of output]
      C:\Users\lenovo\AppData\Local\Temp\pip-build-env-4gje_f0j\overlay\Lib\site-packages\setuptools\_distutils\dist.py:289: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      C:\Users\lenovo\AppData\Local\Temp\pip-build-env-4gje_f0j\overlay\Lib\site-packages\setuptools\_distutils\dist.py:289: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-314\gensim
      copying gensim\downloader.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\interfaces.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\matutils.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\nosy.py -> build\lib.win-amd64-cpython-314\gensim
 

Defaulting to user installation because normal site-packages is not writeable


# Import Required Libraries

In [5]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec


# Sample Dataset

In [6]:
documents = [
    "I love natural language processing",
    "Natural language processing is fun",
    "I love NLP"
]

print(documents)


['I love natural language processing', 'Natural language processing is fun', 'I love NLP']


# Bag of Words – Count Occurrence

In [7]:
count_vectorizer = CountVectorizer()
bow_counts = count_vectorizer.fit_transform(documents)

bow_df = pd.DataFrame(
    bow_counts.toarray(),
    columns=count_vectorizer.get_feature_names_out()
)

bow_df


fun  is  language  love  natural  nlp  processing
0    0   0         1     1        1    0           1
1    1   1         1     0        1    0           1
2    0   0         0     1        0    1           0

# Bag of Words – Normalized Count Occurrence

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()
bow_counts = count_vectorizer.fit_transform(documents)


In [13]:
from sklearn.preprocessing import normalize
import pandas as pd

bow_normalized = normalize(bow_counts, norm='l1')

bow_norm_df = pd.DataFrame(
    bow_normalized.toarray(),
    columns=count_vectorizer.get_feature_names_out()
)

bow_norm_df


fun   is  language  love  natural  nlp  processing
0  0.0  0.0      0.25  0.25     0.25  0.0        0.25
1  0.2  0.2      0.20  0.00     0.20  0.0        0.20
2  0.0  0.0      0.00  0.50     0.00  0.5        0.00

# TF-IDF (Term Frequency – Inverse Document Frequency)

In [14]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf_vectorizer.get_feature_names_out()
)

tfidf_df


fun       is  language      love   natural       nlp  processing
0  0.00000  0.00000  0.500000  0.500000  0.500000  0.000000    0.500000
1  0.51742  0.51742  0.393511  0.000000  0.393511  0.000000    0.393511
2  0.00000  0.00000  0.000000  0.605349  0.000000  0.795961    0.000000

# Tokenize Text for Word2Vec

In [15]:
tokenized_docs = [doc.lower().split() for doc in documents]
tokenized_docs


[['i', 'love', 'natural', 'language', 'processing'],
 ['natural', 'language', 'processing', 'is', 'fun'],
 ['i', 'love', 'nlp']]

# Word Embedding for a Word

In [16]:
word2vec_model = Word2Vec(
    sentences=tokenized_docs,
    vector_size=50,
    window=3,
    min_count=1,
    workers=4
)


In [17]:
word2vec_model.wv['language']


array([-0.01631583,  0.0089916 , -0.00827415,  0.00164907,  0.01699724,
       -0.00892435,  0.009035  , -0.01357392, -0.00709698,  0.01879702,
       -0.00315531,  0.00064274, -0.00828126, -0.01536538, -0.00301602,
        0.00493959, -0.00177605,  0.01106732, -0.00548595,  0.00452013,
        0.01091159,  0.01669191, -0.00290748, -0.01841629,  0.0087411 ,
        0.00114357,  0.01488382, -0.00162657, -0.00527683, -0.01750602,
       -0.00171311,  0.00565313,  0.01080286,  0.01410531, -0.01140624,
        0.00371764,  0.01217773, -0.0095961 , -0.00621452,  0.01359526,
        0.00326295,  0.00037983,  0.00694727,  0.00043555,  0.01923765,
        0.01012121, -0.01783478, -0.01408312,  0.00180291,  0.01278507],
      dtype=float32)

# Similar Words using Word2Vec

In [18]:
word2vec_model = Word2Vec(
    sentences=tokenized_docs,
    vector_size=50,
    window=3,
    min_count=1,
    workers=4
)


In [19]:
word2vec_model.wv['language']


array([-0.01631583,  0.0089916 , -0.00827415,  0.00164907,  0.01699724,
       -0.00892435,  0.009035  , -0.01357392, -0.00709698,  0.01879702,
       -0.00315531,  0.00064274, -0.00828126, -0.01536538, -0.00301602,
        0.00493959, -0.00177605,  0.01106732, -0.00548595,  0.00452013,
        0.01091159,  0.01669191, -0.00290748, -0.01841629,  0.0087411 ,
        0.00114357,  0.01488382, -0.00162657, -0.00527683, -0.01750602,
       -0.00171311,  0.00565313,  0.01080286,  0.01410531, -0.01140624,
        0.00371764,  0.01217773, -0.0095961 , -0.00621452,  0.01359526,
        0.00326295,  0.00037983,  0.00694727,  0.00043555,  0.01923765,
        0.01012121, -0.01783478, -0.01408312,  0.00180291,  0.01278507],
      dtype=float32)

In [20]:
word2vec_model.wv.most_similar('language')


[('i', 0.12486250698566437),
 ('fun', 0.07399576157331467),
 ('processing', 0.04237300902605057),
 ('nlp', 0.018277151510119438),
 ('natural', 0.011071980930864811),
 ('love', -0.17424818873405457),
 ('is', -0.1754782646894455)]

# Sentence Embedding (Average Word Vectors)

In [21]:
def sentence_embedding(sentence, model):
    words = sentence.lower().split()
    vectors = [model.wv[word] for word in words if word in model.wv]
    return np.mean(vectors, axis=0)

sentence_vec = sentence_embedding("I love natural language processing", word2vec_model)
sentence_vec


array([-0.00376068,  0.00078604, -0.00034481,  0.00706779,  0.00535688,
       -0.00080739,  0.00696779,  0.00696501, -0.00817309,  0.005351  ,
       -0.00311161, -0.00381522, -0.00384156,  0.00070413,  0.00322588,
        0.00287029,  0.00868753,  0.00728504, -0.00633655, -0.0025043 ,
        0.00173652, -0.00188444,  0.00614064, -0.00813195,  0.00986166,
       -0.00458918,  0.00116015,  0.0048476 , -0.00532256, -0.00227404,
       -0.00092128, -0.00242629,  0.00472759, -0.00594638, -0.00464129,
       -0.0003795 ,  0.00827134, -0.00448467,  0.00424411,  0.00227431,
       -0.00183217, -0.00065526, -0.005257  , -0.00224707,  0.00309612,
        0.00794056, -0.00154363, -0.00162554, -0.00259297,  0.00835581],
      dtype=float32)